version: "3.3"

services:
  backend:
    build:
      context: ./server/crud # path backend dockerfile
    ports:
      - 8000:8000
    image: backend:appointment
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
  
  frontend:
    build:
      context: ./client/app
    ports: 
      - 5173:5173
    stdin_open: true
    tty: true
    image: frontend:appointment
    container_name: react-frontend
    command: npm start
    depends_on:
      - backend

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nginx-webserver
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend