version: "3.3"

services:
  backend:
    build:
      context: ./server/crud # path backend dockerfile
    ports:
      - 80:80
    image: backend:appointment
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
  
  frontend:
    build:
      context: ./client/app
    ports: 
      - 80:80
    stdin_open: true
    tty: true
    image: frontend:appointment
    container_name: react-frontend
    command: npm start
    depends_on:
      - backend