# Generated by Django 5.0.2 on 2024-09-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='subject',
        ),
    ]
